### ISSUE TITLE
Issue with connecting to add-on and saving the branches

### ISSUE THREAD

**Issue by dana-polishchuk** [osowskit/atlassian-github-app-addon#34] opened 2018-05-24 09:28 UTC
We have added added the add-on , but have a lot of issues

Sometimes it connects to the GitHub account and sometimes gives out errors 
![image](https://user-images.githubusercontent.com/39559118/40476739-726bedac-5f4d-11e8-8d83-bf91f8e0719e.png)
![image 1](https://user-images.githubusercontent.com/39559118/40477018-1fd30642-5f4e-11e8-9e3a-52b9ba21797a.png)

Also the main reason why we need the add on is to show the branch and pull request 
![screenshot_1](https://user-images.githubusercontent.com/39559118/40476883-cf13a112-5f4d-11e8-93b1-5189ff257743.png)

But when we open the ticket from any other browser or user or refresh the page - all the fields above are empty as if nothing was added

**Comment by osowskit** [comment] 2018-05-24 22:05
👋 @dana-polishchuk sorry to hear you are having trouble.

> But when we open the ticket from any other browser ... all the fields above are empty as if nothing was added

This add on is not storing any information in JIRA and relies on the user to log in with their GitHub credentials to view this information. Switching browsers would require logging in on that browser.
 
> refresh the page - all the fields above are empty as if nothing was added

This plugin requires Cookies and JavaScript to work correctly and the following image in the status bar indicates that there may be something that requires your approval: 

<img width="94" alt="screen shot 2018-05-24 at 3 03 08 pm" src="https://user-images.githubusercontent.com/768821/40515921-a178d0d6-5f63-11e8-907c-ba623ab262b8.png">

Could you provide more information about the OS and Browser version you are using and what selecting that icon displays?

**Comment by osowskit** [comment] 2018-05-30 17:54
> As per the storing information, we found a work-around for each developer to login and check in repository for that ticket.

@dana-polishchuk thank you for your understanding. Since different Developers can have access to different Repositories, this app needs each user to authenticate with their own GitHub account.

> But we have a lot of repos and it would be a much appreciated improvement to save to ticket PR added and branch

Selecting multiple repositories in this add on is a new feature. I'm interested to hear more about your workflow to see if I can help optimize this application. How many JIRA projects do you have and how many Repositories do you have associated with each one?

> Also if there are 2 PRs in 1 ticket they will not be automatically parsed.

This should be supported. Here is an example branch being merged into separate targets:

<img width="327" alt="screen shot 2018-05-30 at 10 50 40 am" src="https://user-images.githubusercontent.com/768821/40738178-b31691be-63f7-11e8-9dd0-6fd53c049d91.png">

Could you provide more information on how to reproduce this issue?

**Comment by osowskit** [comment] 2018-06-06 03:36
@dana-polishchuk let me know if you have any additional questions

**Closed** 2018-06-07 18:05 UTC
