### ISSUE TITLE
Customize branch name in branch creation

### ISSUE THREAD

**Issue by taxpon** [osowskit/atlassian-github-app-addon#25] opened 2018-02-14 02:27 UTC
Created  branches through this add-on have each JIRA's issue number as the branch name. I would like to customize branch name like feature/XXXX so that I can follow the git-flow rule.

Thanks in advance.

**Comment by osowskit** [comment] 2018-02-14 03:29
👋 @taxpon - This is a great request and a duplicate of #20. Would every branch be named `feature/XXX` or are there other prefixes you would want to use?

**Comment by taxpon** [comment] 2018-02-14 04:18
@osowskit Oh, sorry for dup. Currently I'd like to use `feature/xxx` only using this add-on.

**Comment by osowskit** [comment] 2018-02-23 23:34
I like the idea of a prefix and may get to this in the next few weeks. Closing in favor of #20

**Closed by osowskit** 2018-02-23 23:34 UTC
Labels: enhancement
